### ISSUE TITLE
Could you help me with this problem?

### ISSUE THREAD

**Issue by burness** [buriburisuri/supervised_infogan#2]
Hi, @buriburisuri Thank you very much with this project, it is very interesting!!!
However, I have a problem to  understand this line here [generator loss](https://github.com/buriburisuri/supervised_infogan/blob/master/train.py#L91). Could you explain the `disc.sg_reuse(input=gen).sg_bce(target=y) `. 
I have check your code in sugartensor, but it seems to be too hard to understand

Thank you again for sharing this project

**Comment by buriburisuri** [comment]
@burness  A month after I'd launched this project, Google published a paper on almost same idea with this project. And I've implemented that paper also.  See https://github.com/buriburisuri/ac-gan instead of this and read Google's paper.  I'll help you.

**Comment by burness** [comment]
@buriburisuri  Thanks! I will read the ac-gan project
